a1 = int(input ("Введите первое число "))
a2 = int(input ("Введите второе число "))
a3 = int(input ("Введите третье число "))
if a1!=a2 and a2!=a3 and a1!=a3: print(0)
if (a1==a2 and a2!=a3) or (a1==a3 and a2!=a3): print(2)
if a1==a2 and a2==a3: print(3)
